# Generated by Django 3.1.7 on 2021-04-10 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.CreateModel(
            name='ScheduledTransaction',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reason', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date_next_due', models.DateField()),
                ('interval_amount', models.IntegerField(default=1)),
                ('interval_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='scheduled_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.scheduledtransaction'),
        ),
    ]
